# Generated by Django 2.1.5 on 2019-04-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailer', '0003_auto_20190429_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebay',
            name='room',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
