# Generated by Django 2.1.5 on 2019-04-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailer', '0004_auto_20190429_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebay',
            name='detail_url',
            field=models.CharField(max_length=200),
        ),
    ]
