# Generated by Django 2.1.5 on 2019-04-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailer', '0006_auto_20190429_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebay',
            name='commision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ebay',
            name='construction_year',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ebay',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='ebay',
            name='features',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ebay',
            name='heating',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ebay',
            name='house_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ebay',
            name='land_area',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ebay',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ebay',
            name='price_negotiable',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
