# Generated by Django 2.1.5 on 2019-04-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailer', '0007_auto_20190429_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebay',
            name='no_of_bedroom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
