# Generated by Django 2.1.5 on 2019-04-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailer', '0008_auto_20190429_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebay',
            name='description',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
    ]
