# Generated by Django 2.1.5 on 2019-04-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailer', '0009_auto_20190429_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebay',
            name='land_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ebay',
            name='living_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
