# Generated by Django 2.1.5 on 2019-04-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailer', '0010_auto_20190429_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebay',
            name='user_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
