# Generated by Django 2.1.5 on 2019-04-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailer', '0012_auto_20190429_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebay',
            name='description',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
    ]
