# Generated by Django 2.1.5 on 2019-04-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailer', '0014_auto_20190429_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebay',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
