# Generated by Django 2.1.5 on 2019-04-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailer', '0015_auto_20190429_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebay',
            name='active_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebay',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ebay',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ebay',
            name='user_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
