# Generated by Django 2.1.5 on 2019-04-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailer', '0018_auto_20190429_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebay',
            name='no_of_bathrooms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
