# Generated by Django 2.1.5 on 2019-04-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etailer', '0019_auto_20190429_1022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ebay',
            unique_together={('detail_url',)},
        ),
    ]
