# Generated by Django 2.1.5 on 2019-04-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailer', '0020_auto_20190429_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebay',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
