# Generated by Django 2.1.5 on 2019-04-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailer', '0021_auto_20190430_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebay',
            name='detail_url',
            field=models.CharField(max_length=300),
        ),
    ]
