# Generated by Django 2.1.5 on 2019-04-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailer', '0022_auto_20190430_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('additional', models.CharField(blank=True, max_length=100, null=True)),
                ('create_dt', models.DateField(auto_now_add=True)),
                ('update_dt', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'homeday',
            },
        ),
        migrations.AlterUniqueTogether(
            name='homeday',
            unique_together={('zip_code',)},
        ),
    ]
