# Generated by Django 2.1.5 on 2019-04-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailer', '0023_auto_20190430_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebay',
            name='description',
            field=models.CharField(blank=True, max_length=11000, null=True),
        ),
    ]
