# Generated by Django 2.1.5 on 2019-04-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etailer', '0024_auto_20190430_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeday',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
