# Generated by Django 2.1.5 on 2019-04-30 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etailer', '0025_homeday_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ebay',
            table='ebay',
        ),
    ]
